### ISSUE TITLE
Easier access to GitHub repo

### ISSUE THREAD

**Issue by mikecroucher** [hpc-uk/hpcuk-website#4]
Would it be possible to make it more obvious to readers of the site that they can contribute via GitHub?  The way we do it at Sheffield is to have a big 'Fork me on GitHub' banner  http://docs.hpc.shef.ac.uk/en/latest/

**Comment by aturner-epcc** [comment]
@mikecroucher Sorry for the slow response on this. This is a really good idea. You can add this yourself via a PR or you can just wait for us to get to it. We will eventually, I promise!

**Comment by aturner-epcc** [comment]
@mikecroucher I have added a link in the menu. The ribbons did not work as they obscured the menu when viewed in mobile mode.
